Added types array to Currency
utily/isoly pull request #38
Opened 2021-03-30 12:36 UTC by robinnedergard

2021-03-30 13:13 UTC, florianebmeier requested changes

2021-03-31 08:17 UTC, florianebmeier requested changes

2021-03-31 08:17 UTC, florianebmeier commented on CurrencyCode.ts
> +		return typeof value == "string" && types.includes(value as any)
Still not resolved

2021-04-08 15:06 UTC, florianebmeier approved these changes

2021-04-09 13:36 UTC, fredrikbryntesson approved these changes

2021-04-09 13:36 UTC, merged