Epoch, TimeSpan and TimeRange
utily/isoly pull request #61
Opened 2021-10-01 08:39 UTC by simonmika

Added epoch function and TimeSpan and TimeRange types.

2021-10-01 10:59 UTC, simonmika commented
@Magnus93, can you take a look at this and if you are happy.

2021-10-01 12:05 UTC, Magnus93 requested changes

2021-10-01 12:05 UTC, Magnus93 commented on .vscode/settings.json
> +	"cSpell.words": [
Add nececery extension in `.vscode/extensions.json`

2021-10-01 12:11 UTC, Magnus93 commented
Also make parity branch

2021-10-04 07:21 UTC, Magnus93 approved these changes, later dismissed

2021-10-04 12:25 UTC, fredrikbryntesson approved these changes

2021-10-04 12:26 UTC, merged