Seemingly working calculations.
utily/isoly pull request #65
Opened 2021-11-23 07:19 UTC by marcushanses

2021-11-23 08:53 UTC, robinnedergard submitted a review, later dismissed
Make parity

2021-11-23 09:34 UTC, Magnus93 approved these changes, later dismissed

2021-11-24 15:04 UTC, nilssonemma submitted a review, later dismissed

2021-11-24 15:09 UTC, robinnedergard approved these changes, later dismissed

2021-11-24 16:03 UTC, Magnus93 approved these changes

2021-11-24 16:04 UTC, Magnus93 approved these changes, later dismissed

2021-11-25 14:26 UTC, robinnedergard approved these changes, later dismissed

2021-11-25 15:16 UTC, Magnus93 approved these changes

2021-11-25 16:21 UTC, Magnus93 requested changes

2021-11-25 16:21 UTC, Magnus93 commented on Currency.ts
> +	export function multiply(currency: Currency, value1: number, value2: number): number {
Just realized that you are multiplying a currency with a qouta (andel). Not a currency with a currency e.g. `SEK*SEK = SEK^2` makes no sense. So only value1 should be made into minor units. Same for division.

Also you should be able to calculate e.g. SEK to ISK. So I suggest a 4th optional `outputCurrency` argument.

2021-11-29 12:39 UTC, Magnus93 approved these changes

2021-11-29 22:42 UTC, fredrikbryntesson approved these changes

2021-11-29 22:43 UTC, merged