Currency calculator.
utily/isoly pull request #66
Opened 2021-11-23 09:20 UTC by marcushanses

2021-11-23 09:34 UTC, Magnus93 approved these changes, later dismissed

2021-11-24 15:05 UTC, nilssonemma submitted a review, later dismissed

2021-11-24 15:09 UTC, robinnedergard approved these changes

2021-11-24 15:09 UTC, robinnedergard approved these changes, later dismissed

2021-11-25 08:46 UTC, robinnedergard approved these changes, later dismissed

2021-11-25 15:15 UTC, Magnus93 approved these changes

2021-11-25 16:23 UTC, Magnus93 requested changes

2021-11-25 16:23 UTC, Magnus93 commented on Currency.ts
> +	export function multiply(currency: Currency, value1: number, value2: number): number {
Don't muliply currency with currency. Only convert value1 to minor units. Same for division.

2021-11-26 08:36 UTC, fredrikbryntesson approved these changes, later dismissed

2021-11-29 12:39 UTC, Magnus93 approved these changes

2021-11-29 22:43 UTC, fredrikbryntesson approved these changes

2021-11-29 22:43 UTC, merged